### PR TITLE
option to select your prefered icon theme

### PR DESCRIPTION
**Pull request by paixeww**
adds support for more icon themes and folder colors. 

papirus-folders can dynamically change folder colors I think that would look cool with your color change script.
look into it if you are interested

### CODE REVIEW

**Comment by paixeww** [comment]
Now compatible

**Comment by koeqaife** [comment]
Okay, have you tested everything?

**Comment by koeqaife** [comment]
image
hm

**Comment by paixeww** [comment]
Damn small typo..

**Comment by koeqaife** [comment]
image
Papirus folder color is always blue, I think it's gtk problem

**Comment by koeqaife** [comment]
or nautilus problem

**Comment by koeqaife** [comment]
And idk why after using super+shift+w icon theme is ''

**Comment by koeqaife** [comment]
but if I use `python -O ~/dotfiles/hypr/scripts/wallpaper.py -R -n` everything is ok

**Comment by paixeww** [comment]
> or nautilus problem

Try 'kill nautilus' after changing. I have heard about that

**Comment by paixeww** [comment]
> but if I use `python -O ~/dotfiles/hypr/scripts/wallpaper.py -R -n` everything is ok

Strange... How come shortcut differ??

**Comment by koeqaife** [comment]
> Try 'kill nautilus' after changing. I have heard about that

doesn't work haha

**Comment by koeqaife** [comment]
I'm trying to improve on everything you've done and fix some things

**Comment by koeqaife** [comment]
> > but if I use `python -O ~/dotfiles/hypr/scripts/wallpaper.py -R -n` everything is ok
> 
> Strange... How come shortcut differ??

I think the problem is that you wrote the relational path and not the full path to the icon-theme file

**Comment by paixeww** [comment]
Yeah go ahead I'm not the best in BASH :]

**Comment by paixeww** [comment]
> > > but if I use `python -O ~/dotfiles/hypr/scripts/wallpaper.py -R -n` everything is ok
> 
> > 
> 
> > Strange... How come shortcut differ??
> 
> 
> 
> I think the problem is that you wrote the relational path and not the full path to the icon-theme file

Yeah... my bad forgot to change it to absolute path

**Comment by paixeww** [comment]
> > Try 'kill nautilus' after changing. I have heard about that
> 
> 
> 
> doesn't work haha

I will look into that

**Comment by paixeww** [comment]
if you add the gum choice --height=20 to tela icons installer I think it would be better

**Comment by koeqaife** [comment]
idk

**Pull request merged**
